baseURL = "https://quartz.jzhao.xyz/"
languageCode = "en-us"
relativeURLs = false
disablePathToLower = true
ignoreFiles = [
    "/content/templates/*",
    "/content/private/*",
]
summaryLength = 20
paginate = 10
enableGitInfo = true

[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        anchorLineNos = false
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        style = "dracula"
    [frontmatter]
        lastmod = ["lastmod", ":git", "date", "publishDate"]
        publishDate = ["publishDate", "date"]
    [markup.goldmark.renderer]
        unsafe = true
ignoreFiles = [  
    "/content/templates/*",  
    "/content/private/*", 
    "content/notes/.obsidian/app.json",
    "content/notes/.obsidian/appearance.json",
    "content/hagen/.obsidian/core-plugins-migration.json -> content/notes/.obsidian/core-plugins-migration.json",
    "content/hagen/.obsidian/core-plugins.json -> content/notes/.obsidian/core-plugins.json",
    "content/notes/.obsidian/hotkeys.json",
    "content/notes/.obsidian/workspace.json",
    "content/hagen/.obsidian/app.json -> content/notes/hagen/.obsidian/app.json",
    "content/hagen/.obsidian/appearance.json -> content/notes/hagen/.obsidian/appearance.json",
    "content/hagen/.obsidian/community-plugins.json -> content/notes/hagen/.obsidian/community-plugins.json",
    "content/notes/hagen/.obsidian/core-plugins-migration.json",
    "content/notes/hagen/.obsidian/core-plugins.json",
    "content/hagen/.obsidian/hotkeys.json -> content/notes/hagen/.obsidian/hotkeys.json",
    "content/hagen/.obsidian/plugins/obsidian-hider/main.js -> content/notes/hagen/.obsidian/plugins/obsidian-hider/main.js",
    "content/hagen/.obsidian/plugins/obsidian-hider/manifest.json -> content/notes/hagen/.obsidian/plugins/obsidian-hider/manifest.json",
    "content/hagen/.obsidian/plugins/obsidian-hider/styles.css -> content/notes/hagen/.obsidian/plugins/obsidian-hider/styles.css",
    "content/hagen/.obsidian/plugins/obsidian-linter/main.js -> content/notes/hagen/.obsidian/plugins/obsidian-linter/main.js",
    "content/hagen/.obsidian/plugins/obsidian-linter/manifest.json -> content/notes/hagen/.obsidian/plugins/obsidian-linter/manifest.json",
    "content/hagen/.obsidian/plugins/obsidian-linter/styles.css -> content/notes/hagen/.obsidian/plugins/obsidian-linter/styles.css",
    "content/hagen/.obsidian/plugins/obsidian-style-settings/main.js -> content/notes/hagen/.obsidian/plugins/obsidian-style-settings/main.js",
    "content/hagen/.obsidian/plugins/obsidian-style-settings/manifest.json -> content/notes/hagen/.obsidian/plugins/obsidian-style-settings/manifest.json",
    "content/hagen/.obsidian/plugins/obsidian-style-settings/styles.css -> content/notes/hagen/.obsidian/plugins/obsidian-style-settings/styles.css",
    "content/hagen/.obsidian/plugins/templater-obsidian/main.js -> content/notes/hagen/.obsidian/plugins/templater-obsidian/main.js",
    "content/hagen/.obsidian/plugins/templater-obsidian/manifest.json -> content/notes/hagen/.obsidian/plugins/templater-obsidian/manifest.json",
    "content/hagen/.obsidian/plugins/templater-obsidian/styles.css -> content/notes/hagen/.obsidian/plugins/templater-obsidian/styles.css",
    "content/hagen/.obsidian/themes/AnuPpuccin/manifest.json -> content/notes/hagen/.obsidian/themes/AnuPpuccin/manifest.json",
    "content/hagen/.obsidian/themes/AnuPpuccin/theme.css -> content/notes/hagen/.obsidian/themes/AnuPpuccin/theme.css",
    "content/hagen/.obsidian/workspace.json -> content/notes/hagen/.obsidian/workspace.json",
]
